### PR TITLE
In plugin.py, there is an fix of resource format key error

### PR DESCRIPTION
**Pull request by Nisha1293**
This is the fix of resource format key error

### CODE REVIEW

**Comment by Nisha1293** [comment]
Hi @duttonw 
I have raised one PR.  Could you please review it.

**Comment by duttonw** [comment]
Hi @Nisha1293,

Can you enable github actions on your repo and retrigger the build so i can review the tests etc.
https://github.com/Nisha1293/ckanext-xloader/actions

regards,

@duttonw

**Comment by ThrawnCA** [comment]
I don't understand what situation would fail to have a format.

**Comment by duttonw** [comment]
I think its in relation to not having 'format' in the dict. Some ckan admin's may have decided to drop that field on their servers.

**Comment by ThrawnCA** [comment]
> Some ckan admin's may have decided to drop that field on their servers.

And still run XLoader, which relies on the format field to know whether it should try to parse a resource? That seems very odd indeed.

**Comment by duttonw** [comment]
@ThrawnCA, I don't see any issue in merging this since its just wrapped it in a null safe context. 

Your thoughts?

**Comment by ThrawnCA** [comment]
> Your thoughts?

I suppose it's harmless, it just seems very odd for anyone to need this null-check.

**Review by duttonw — APPROVED** [review]

**Pull request merged**
