### PR TITLE
chore: switch to pyproject.toml

### PR DESCRIPTION
**Pull request by duttonw**
Per: https://github.com/ckan/ckanext-xloader/pull/235#discussion_r1853690867

### CODE REVIEW

**Comment by duttonw** [comment]
Hi (@ThrawnCA , @JVickery-TBS , @amercader , @davidread , @kowh-ai , @pdelboca , @wardi )

Can you confirm and let me know if you are happy to be listed on the authors/maintainers as well as if that is your preferred email address.

I've ordered the authors based on most recent work as well as most contributions and maintainers via pypi listing. (tho with how we have just configured github actions auto deploy, that list may need to reflect who has 'maintainer' rights on this project  (who can cut versions etc).


Regards,

@duttonw

**Comment by ThrawnCA** [comment]
@duttonw I'd prefer to use my work email for this repo.

**Review by ThrawnCA — APPROVED** [review]

**Comment by davidread** [comment]
Thanks for this, but please just use my name, not email

**Comment by JVickery-TBS** [comment]
@duttonw Yeah that sounds great! And yeah that account is good (for now, will let you know if I move from TBS and then we can move to my personal github).

Currently I do not have a lot of capacity, but hopefully will be able to do some small bug reports and fixes.

**Comment by duttonw** [comment]
@davidread 
> Thanks for this, but please just use my name, not email

removed.

**Comment by duttonw** [comment]
Hi ( @amercader , @kowh-ai , @pdelboca , @wardi ),

Just a reminder to ensure you happy with or with to have alterations on the author/maintainer details (name/email component).

I'm looking at merging this PR on the 4th of Dec 2024 as I've had 50% response rate on their preference with said details.

Regards,

@duttonw

**Comment by amercader** [comment]
@duttonw Keeping mine is fine, but I think it's safer to not include emails unless people have given explicit consent, as these will pop up in pypi or be inevitably harvested for spam.

**Pull request merged**
