### PR TITLE
Update Travis Setup

### PR DESCRIPTION
**Pull request by kowh-ai**
Update the Travis files to align with the other CKAN 2.9 Extensions

### CODE REVIEW

**Comment by kowh-ai** [comment]
@davidread - hey David:  any idea why this PR is not triggering at Travis CI? (https://travis-ci.org/github/ckan/ckanext-xloader/pull_requests). The "Update-Travis-Setup" branch triggered a Travis build but not the PR (nor update to the PR)

**Comment by davidread** [comment]
@kowh-ai It's enabled in Travis still 🤷 .

I think it might be to do with the deprecation of the triggering from GitHub: https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/ which would affect Travis for all repos in the CKAN GitHub org. However we've had builds a month ago, so I'm not sure why it's only occurred more recently. But it seems like a migration that should be done. There is a way to migrate them all at once here: https://travis-ci.com/organizations/ckan/repositories but I'll leave you to discuss that amongst the ckan tech team.

**Comment by kowh-ai** [comment]
@davidread - thanks David - ended up being a problem with parsing my .travis.yml file (oops) - the Travis build is now green for all CKAN/Python releases 👍

**Comment by amercader** [comment]
Great work @kowh-ai !

**Pull request merged**
