### PR TITLE
Bring 2.9-fixes branch up to date with master

### PR DESCRIPTION
**Pull request by ThrawnCA**
Also clean up for Flake8.

### CODE REVIEW

**Comment by amercader** [comment]
Thansk @ThrawnCA, Python 3 / CKAN 2.9 support was added in #113

**Comment by amercader** [comment]
Sorry, maybe I was too hasty in closing this, @ThrawnCA is this still relevant against current master?

**Comment by ThrawnCA** [comment]
This does need a merge of latest master changes and some rework, but I think it will still add some value when done.

I notice that in the process of adding Click support, you've dropped paster support. Isn't it possible to support both?

**Comment by ThrawnCA** [comment]
@amercader This now just fixes a few Flake8 issues.

**Pull request merged**
